//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IVDecision.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_IVDECISION_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDR_MENU                        129
#define IDR_TOOLBAR1                    130
#define IDR_TOOLBAR_USER                132
#define IDD_DATASEND                    134
#define IDD_DLG_RNDF                    135
#define IDB_BITMAPGREN                  136
#define IDB_BITMAPRED                   137
#define IDC_STATIC_MAP                  1000
#define IDC_OPENVELLISTEN               1002
#define IDC_OPENSIGHTLISTEN             1003
#define IDC_DATASENDTEST                1005
#define IDC_TURN                        1006
#define IDC_BRAKE                       1007
#define IDC_VELOCITY                    1008
#define IDC_LAT                         1011
#define IDC_AZIMUTH                     1012
#define IDC_VIEWONOFF                   1013
#define IDC_LON                         1014
#define IDC_EXCUTIONSTART               1018
#define IDC_EXECUTIONSTART              1018
#define IDC_BUTTON2                     1019
#define IDC_EXECUTIONSTOP               1019
#define IDC_CONSEND                     1019
#define IDC_BTN_RNDFGBXY                1019
#define IDC_STARTTEST                   1020
#define IDC_LAODRNDF                    1021
#define IDC_BTN_RNDFQJGPS               1023
#define IDC_STATIC_RNDF_GPSMAP          1024
#define IDC_STATIC_RNDF_XYMAP           1025
#define IDC_BTN_RNDFEXIT                1026
#define IDC_BTN_RNDFMATCH               1027
#define IDC_BTN_RNDFROT                 1028
#define IDC_EDIT_RNDF_ROT               1029
#define IDC_BTN_FLIPH                   1030
#define IDC_BTN_FLIPV                   1031
#define IDC_COMBO1                      1032
#define IDC_COMBO_COM                   1032
#define IDC_EDIT2                       1033
#define IDC_COMBOBOXEX1                 1034
#define IDC_CARD1                       1035
#define IDC_CARD2                       1036
#define IDC_C_SPEED                     1037
#define IDC_EDIT3                       1038
#define IDC_EDIT_CTR                    1038
#define IDC_EDIT4                       1039
#define IDC_SET_SPEED1                  1039
#define IDC_SET_SPEED2                  1040
#define IDC_BUTTONZXZB                  1041
#define IDC_SET_SPEED3                  1041
#define IDC_BUTTONZDZB                  1042
#define IDC_SET_SPEED4                  1042
#define IDC_BUTTONJT                    1043
#define IDC_SET_SPEED5                  1043
#define IDC_BUTTONFW                    1044
#define IDC_BUTTON7                     1045
#define IDC_BUTTONZL                    1045
#define IDC_RNDF                        1048
#define IDC_BUTTON3                     1049
#define IDC_BUTTON_LoadMDF              1049
#define IDC_READRNDF                    1049
#define IDC_lukou_zuo                   1049
#define IDC_BUTTON4                     1050
#define IDC_lukou_you                   1050
#define IDC_EDIT6                       1053
#define IDC_SIGN                        1054
#define IDC_EDIT12                      1054
#define IDC_rightrearspd                1054
#define IDC_TOP_DECISION                1055
#define IDC_SECOND_DECISION             1056
#define IDC_LOADRNDF2                   1057
#define IDC_ANIMATE1                    1058
#define IDC_GLOBAL_PLAN                 1059
#define IDC_EDIT13                      1065
#define IDC_EDIT14                      1066
#define IDC_CHECK1                      1067
#define IDC_EDIT15                      1068
#define IDC_SET_SEED                    1072
#define IDC_SET_SPEED                   1072
#define IDC_Title                       1073
#define IDC_CONNECT_GPS                 1075
#define IDC_PATH_FOLLOW                 1076
#define IDC_BUTTON1                     1078
#define IDC_lukou_zhi                   1078
#define IDC_RADIO4                      1080
#define IDC_RADIO5                      1081
#define IDC_RADIO6                      1082
#define IDC_lukou_diaotou               1083
#define IDC_BUTTON6                     1084
#define IDC_lukouchu                    1084
#define IDC_Swan                        1085
#define IDC_BUTTON5                     1086
#define IDC_person                      1086
#define IDC_laneseq                     1087
#define IDC_lanenum                     1088
#define IDC_setlane                     1089
#define IDC_lanechgqian                 1090
#define IDC_lanechghou                  1091
#define IDC_shigong                     1092
#define IDC_CHECK2                      1093
#define IDC_CHECK3                      1094
#define IDC_apapath1                    1095
#define IDC_apapath2                    1096
#define IDC_apapath3                    1097
#define IDC_leftfrontdist               1098
#define IDC_leftfrontspd                1099
#define IDC_leftreardist                1100
#define IDC_leftrearspd                 1101
#define IDC_rightfrontdist              1102
#define IDC_rightfrontspd               1103
#define IDC_rightreardist               1104
#define IDC_middlefrontdist             1105
#define IDC_middlefrontspd              1106
#define IDC_bobfrontlchgreqdisp         1107
#define IDC_bobleftlchgnotalooweddisp   1108
#define IDC_bobrightlchgnotalooweddisp  1109
#define IDC_EDIT21                      1110
#define IDC_bobfrontlchgnotalooweddisp  1110
#define IDC_speediniset                 1111
#define IDC_laneexist                   1112
#define IDC_ApaStrtLat                  1113
#define IDC_ApaStrtLng                  1114
#define IDC_ApaEndLat                   1115
#define IDC_EDIT8                       1116
#define IDC_ApaEndLng                   1116
#define ID_32771                        32771
#define ID_32772                        32772
#define ID_TB_EXEDEBUG                  32773

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
